# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install
        run: yarn install --frozen-lockfile

      - name: build
        run: yarn build
        env:
          GITHUB_API_TOKEN: ${{secrets.GITHUBAPI_TOKEN}}
        
      - name: deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
          GH_PAT: ${{secrets.GITHUB_API_KEY}}
          BUILD_DIR: "public/"
